export const projects = [
  {
    id: 1,
    title: "PS and Sons Construction",
    description:
      "A business website designed to drive growth for PS & Sons Construction. Features a clean, modern UI that highlights core services, making it easy for clients to connect and request estimates. Enhanced local SEO and online presence have expanded client reach and improved discoverability beyond word-of-mouth.",
    image: "/projects/psandsonsproject.png",
    tags: ["React.js", "TailwindCSS", "Web3Forms"],
    demoUrl: "",
    youtubeUrl: "",
    gitHubUrl: "https://github.com/Joel-sari/PS-SonsConstructionLLC",
    date: "August 2025",
    sortDate: "2025-08-01",
  },
  {
    id: 2,
    title: "CryptoWatch",
    description:
      "A real-time cryptocurrency dashboard that tracks prices, volume, and market trends. Designed for clarity and usability, it presents complex data in an accessible format, empowering users to stay informed and make timely decisions.",
    image: "/projects/cryptowatchproject.png",
    tags: ["React.js", "CSS", "CoinGecko API"],
    demoUrl: "",
    youtubeUrl: "",
    gitHubUrl: "https://github.com/Joel-sari/CryptoWatch",
    date: "June 2025",
    sortDate: "2025-06-01",
  },
  {
    id: 3,
    title: "Investment Calculator",
    description:
      "A tool that helps users visualize the growth of their investments over time. By making financial projections easy to understand, it supports better decision-making and empowers users to plan for their financial goals.",
    image: "/projects/investmentcalculatorproject.png",
    tags: ["React.js", "CSS"],
    demoUrl: "",
    youtubeUrl: "",
    gitHubUrl: "https://github.com/Joel-sari/InvestmentCalculator",
    date: "July 2025",
    sortDate: "2025-07-01",
  },
  {
    id: 4,
    title: "Movie Store",
    description:
      "A feature-rich movie e-commerce platform built with Django, showcasing user authentication, dynamic content management, and an integrated shopping cart/checkout system. Users can browse movies, view details, manage their carts, and complete purchases with automatically generated orders.",
    longDescription:
      "GT Movie Store is a full‑stack Django web app I built for a course to practice real e‑commerce patterns. It includes authentication, session‑based carts, order generation, and deployment on PythonAnywhere. This project let me solidify Django’s model‑view‑template flow and how to ship changes to production.",
    process: [
      "Scoped features into auth, catalog, cart, and orders to ship incrementally",
      "Debugged responsiveness issues (Safari/Chrome) and standardized image ratios",
      "Set up migrations/fixtures, static collection, and a deployment workflow",
      "Documented known trade‑offs and next steps (payments, search, admin polish)",
    ],
    image: "/projects/moviestoreproject.png",
    tags: ["Django", "SQLite", "BootstrapCSS", "Python"],
    demoUrl: "https://joelsari.pythonanywhere.com/",
    youtubeUrl: "https://www.youtube.com/watch?v=zOADQZK_7g4",
    gitHubUrl: "https://github.com/Joel-sari/JoelsMovieStore",
    date: "September 2025",
    sortDate: "2025-09-01",
  },
  {
    id: 5,
    title: "Joel's Personal Portfolio",
    description:
      "A custom-built portfolio website designed with React and TailwindCSS, featuring smooth animations and a responsive layout across all devices. It not only showcases my projects but also highlights his skills, background, and professional journey. The site includes an integrated contact form, links to social platforms, and a dedicated skills section.",
    image: "/projects/JoelSariPortfolioProject.png",
    tags: ["React.js", "TailwindCSS", "Web3Forms"],
    demoUrl: "#",
    youtubeUrl: "",
    gitHubUrl: "https://github.com/Joel-sari/Joel-s-Personal-Portfolio/",
    date: "September 2025",
    sortDate: "2025-09-01",
  },
  {
    id: 6,
    title: "SHPE Georgia Tech Member Portal",
    description:
      "Chapter website and member portal used by 500+ students — events & RSVPs, membership, admin tools, and sponsor-facing pages.",
    longDescription:
      "Collaborative project built by the SHPE GT IT team. The portal supports membership management, event RSVPs, admin-only workflows, and sponsor engagement. I contributed UI flows, data wiring, and feature enhancements, focusing on reliability, clear UX, and smooth admin operations.",
    contributions: [
      "Built/updated member flows (RSVP, profile, announcements) and admin dashboard views",
      "Wired data reads/writes and media storage; tuned auth/roles with the team",
      "Polished UX/accessibility, fixed bugs, and coordinated small releases",
    ],
    image: "/projects/SHPEGT.png",
    tags: ["React.ts", "Astro", "Firebase", "AWS S3", "TailwindCSS"],
    demoUrl: "https://gt-shpe.com/",
    youtubeUrl: "",
    gitHubUrl: "",
    privateRepo: true,
    collaboration: "Team",
    role: "IT Chair (Developer)",
    org: "SHPE Georgia Tech",
    date: "September 2025",
    sortDate: "2025-09-02",
  },
  {
    id: 7,
    title: "CareerHub",
    description:
      "CareerHub enables recruiters to post jobs, review applicants, and visualize candidate interest. Job seekers can browse personalized recommendations, track application statuses, and manage profiles in a clean, responsive UI.",
    longDescription:
      "CareerHub is a full-stack platform I built to streamline the hiring workflow for recruiters and job seekers. It features dynamic dashboards, real-time maps, role-based authentication, job recommendations, and an elegant UI powered by React + TailwindCSS. On the backend, Django REST Framework handles all API endpoints for jobs, applications, and user profiles. The system supports job posting, resume submissions, an applicant directory, recruiter pipelines, and interactive map views of postings and candidate clusters.",
    contributions: [
      "Implemented recruiter and job-seeker dashboards with polished, modern interfaces",
      "Built the interactive job map using Google Maps API with dynamic pin rendering",
      "Developed job posting, application tracking, and candidate directory workflows",
      "Created REST API endpoints for jobs, applications, messaging, and profiles",
      "Improved user experience with responsive layouts, hover interactions, and reusable UI components",
    ],
    image: "/projects/CareerHubProject.png",
    tags: ["React.js", "TailwindCSS", "Django", "REST API", "Google Maps API"],
    demoUrl: "https://careerhub-joelsari.pythonanywhere.com",
    youtubeUrl: "",
    gitHubUrl: "https://github.com/Joel-sari/CareerHub",
    role: "Team Lead & Product Owner",
    collaboration: "Team",
    org: "",
    date: "November 2025",
    sortDate: "2025-11-18",
  },
  {
    id: 8,
    title: "Reverie",
    description:
      "An award-winning iOS app that transforms user dreams into interactive DreamCards using Apple’s on-device Foundation Model and CoreML Stable Diffusion. Features dream logging, AI-assisted dream completion, and a dynamic dreamscape visualization.",
    longDescription:
      "Reverie helps users capture dreams instantly and explore deeper meaning through AI-driven insights. I contributed to dream logging features, DreamCard generation animations, CoreML image generation, and the character unlock system. Reverie won Best Design and Best App at Georgia Tech’s iOS Club Demo Day.",
    contributions: [
      "Engineered the DreamCard UI using SwiftUI’s layout system with layered Z‑stacks, gradients, and dynamic geometry effects",
      "Implemented custom 3D flip animations using rotation effects, spring animations, and state‑driven view transitions",
      "Developed physics‑inspired floating and flickable sticker interactions using gesture handlers, interpolation, and velocity-based animations",
      "Built a persistent pinning system backed by UserDefaults with real‑time UI state synchronization across multiple views",
      "Optimized the sticker grid rendering by implementing pin‑priority sorting logic and reducing unnecessary SwiftUI recompositions",
    ],
    image: "/projects/reverieproject.jpg",
    tags: [
      "SwiftUI",
      "CoreML",
      "Stable Diffusion",
      "Firebase",
      "Foundation Model",
    ],
    demoUrl: "",
    youtubeUrl:
      "https://www.linkedin.com/feed/update/urn:li:activity:7398080601938939904/",
    gitHubUrl: "https://github.com/gtiosclub/Reverie",
    privateRepo: true,
    collaboration: "Team",
    role: "iOS Developer",
    org: "GT iOS Club",
    date: "November 2025",
    sortDate: "2025-11-28",
  },
  {
    id: 9,
    title: "HelloWorld",
    description:
      "A full-stack travel memory app with an interactive 3D globe where users drop location-based pins with photos and captions, react to pins, and explore their own and friends’ memories in a modern Apple Photos-style gallery.",
    longDescription:
      "HelloWorld is a full-stack Django + Three.js web app that lets users capture and explore memories around the world on an interactive 3D globe. Users create geocoded pins using City/State/Country (no raw lat/lon), attach up to five photos per pin (cover + additional images via PinPhoto), and view clean hover/click pin details. The app includes a friends system to add friends and browse friends’ pins, reaction support with shared counts across viewers, and customizable user profiles with avatar options. A dedicated gallery page provides an Apple Photos-inspired browsing experience with responsive layout, filtering, and search/sort tools.",
    contributions: [
      "Built a Three.js globe UI with accurate spherical pin rendering, hover previews, and click-to-open pin details",
      "Implemented City/State/Country pin creation with OpenCage geocoding to replace manual latitude/longitude input",
      "Designed a multi-photo architecture (Pin.image + PinPhoto) supporting up to 5 photos per pin with selective add/remove edit workflows",
      "Developed a friends system with endpoints and UI to add friends and view friends’ pins",
      "Added reaction functionality and compact, polished reaction-count UI for pin overlays",
      "Created an Apple Photos-style gallery with responsive grid, country filters, and search/sort UX",
      "Implemented customizable profiles with avatar support and improved modal/overlay UX",
    ],
    image: "/projects/helloworldproject.png",
    tags: [
      "Django",
      "Three.js",
      "Vanilla JS",
      "SQLite",
      "OpenCage API",
      "Python",
    ],
    demoUrl: "https://helloworld-joelsari.pythonanywhere.com",
    youtubeUrl: "",
    gitHubUrl: "https://github.com/Joel-sari/Hello-World",
    date: "December 2025",
    sortDate: "2025-12-01",
    collaboration: "Team",
    role: "Technical Lead",
  },
  {
    id: 10,
    title: "Terminal Snake Game (C)",
    description:
      "A fully custom Snake game built in pure C with real‑time keyboard input, Unicode graphics, ANSI rendering, Hard Mode obstacles, Wrap Mode, smooth game‑over flow, and dynamic speed scaling.",
    longDescription:
      "A systems‑level C project showcasing low‑level input handling, terminal control using ANSI escape codes, game loop architecture, and memory‑safe board rendering. Features include live movement without the Enter key (raw mode), UTF‑8 graphics (█ ● ○ ◆), dynamic obstacle generation, Wrap Mode teleportation, Hard Mode with difficulty scaling, pause/restart controls, and a polished UI flow across start, gameplay, pause, and game‑over screens.",
    contributions: [
      "Implemented real‑time input using termios raw mode for instant movement",
      "Architected the full game loop (input → update → physics → render)",
      "Developed ANSI‑based rendering for flicker‑free terminal animations",
      "Built Hard Mode with dynamic obstacle generation and collision detection",
      "Added Wrap Mode with coordinate‑wrapping edge behavior",
      "Created smooth pause and game‑over UI screens with restart flow",
      "Designed all board visuals using UTF‑8 characters for a clean aesthetic",
    ],
    image: "/projects/snakegameproject.png",
    tags: ["C", "ANSI", "Systems Programming", "Terminal"],
    demoUrl: "",
    youtubeUrl: "https://youtu.be/zkPb9qJdsOI",
    gitHubUrl: "https://github.com/Joel-sari/snake-game.git", // replace with final repo URL
    date: "December 2025",
    sortDate: "2025-12-15",
    collaboration: "Solo",
    role: "Developer",
  },
];
